In [ ]:
!pip install tensorflow

In [ ]:
!pip install keras

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras 
from keras.models import Sequential
from keras.layers import Dropout,Activation,Dense
from keras.optimizers import serialize
from tensorflow.keras.utils import to_categorical

# **Data Loading and Train Test split**

In [ ]:
D2 = pd.read_csv("/content/D2.csv")
D2 = pd.DataFrame(D2)
D2.tail()

class  X1A  X1C  X1G  X2A  X2C  X2G  X3A  X3C  X3G  ...  X57G  X58A  \
3170     N    0    0    0    0    1    0    0    0    0  ...     0     0   
3171     N    0    0    1    1    0    0    0    0    1  ...     1     0   
3172     N    0    0    0    0    1    0    0    0    0  ...     0     0   
3173     N    1    0    0    0    0    0    0    0    0  ...     0     0   
3174     N    1    0    0    0    0    1    0    0    1  ...     0     1   

      X58C  X58G  X59A  X59C  X59G  X60A  X60C  X60G  
3170     1     0     0     0     0     0     0     0  
3171     1     0     0     0     0     0     0     1  
3172     0     1     0     0     0     0     1     0  
3173     1     0     1     0     0     1     0     0  
3174     0     0     0     0     0     0     0     0  

[5 rows x 181 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
X = pd.DataFrame(D2.drop(["class"],axis = 1)).values
y = pd.DataFrame(pd.DataFrame(D2["class"]).values.reshape(-1,1))
y = np.array(pd.get_dummies(y))

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 66302077)
y_test


print(y_test.shape)

(635, 3)


# **Model Creation**

In [ ]:
RNN = Sequential()
RNN.add(Dense(100,activation = "sigmoid",input_dim = 180))
RNN.add(Dropout(0.6))
RNN.add(Dense(80,activation = "sigmoid"))
RNN.add(Dropout(0.6))
RNN.add(Dense(50,activation = "sigmoid"))
RNN.add(Dropout(0.5))
RNN.add(Dense(20,activation = "sigmoid"))
RNN.add(Dropout(0.5))
RNN.add(Dense(3,activation = "softmax"))


# **Model compile**

In [ ]:
RNN.compile(loss = "categorical_crossentropy",metrics = ["accuracy"])

# **Model fitting**

In [ ]:
RNN.fit(X_train,y_train,batch_size = 64,epochs = 500)

Epoch 1/500
40/40 [==============================] - 0s 5ms/step - loss: 0.0683 - accuracy: 0.9772
Epoch 2/500
40/40 [==============================] - 0s 5ms/step - loss: 0.0603 - accuracy: 0.9799
Epoch 3/500
40/40 [==============================] - 0s 4ms/step - loss: 0.0575 - accuracy: 0.9850
Epoch 4/500
40/40 [==============================] - 0s 5ms/step - loss: 0.0556 - accuracy: 0.9850
Epoch 5/500
40/40 [==============================] - 0s 4ms/step - loss: 0.0485 - accuracy: 0.9862
Epoch 6/500
40/40 [==============================] - 0s 5ms/step - loss: 0.0654 - accuracy: 0.9854
Epoch 7/500
40/40 [==============================] - 0s 9ms/step - loss: 0.0551 - accuracy: 0.9843
Epoch 8/500
40/40 [==============================] - 0s 6ms/step - loss: 0.0573 - accuracy: 0.9823
Epoch 9/500
40/40 [==============================] - 0s 4ms/step - loss: 0.0489 - accuracy: 0.9858
Epoch 10/500
40/40 [==============================] - 0s 3ms/step - loss: 0.0585 - accuracy: 0.9850
Epoch 11/

# **Model Evaluation**

In [ ]:
score = RNN.evaluate(X_test,y_test,batch_size = 64)

10/10 [==============================] - 0s 2ms/step - loss: 0.5355 - accuracy: 0.9465


In [ ]:
y_pred = RNN.predict(X_test)
np.round(y_pred,5)

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
y_original_pred = np.argmax(y_pred,axis = 1)

In [ ]:
from sklearn.preprocessing import LabelEncoder
t = LabelEncoder()
y_original = t.fit_transform(D2["class"])
y_original
X_train,X_test,y_original_train,y_original_test = train_test_split(X,y_original,test_size = 0.2,random_state = 66302077)
y_original_test

array([2, 2, 0, 1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 0, 0, 1, 2, 0,
       1, 2, 2, 0, 1, 2, 2, 2, 1, 1, 0, 0, 0, 1, 2, 1, 1, 0, 2, 2, 2, 0,
       2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       1, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 1, 2, 2, 2,
       1, 0, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2,
       2, 1, 0, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 1, 2, 2, 0, 1, 2, 2, 2, 2,
       2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 0, 0, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 2, 0, 2, 0, 0, 2, 0,
       2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
       2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 0, 2, 1, 1, 0, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 1, 1, 2, 2, 2, 1, 1, 2,
       1, 2, 0, 2, 1, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 1, 2, 2, 1, 2, 2,
       2, 1, 1, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2,

In [ ]:
print(confusion_matrix(y_original_test,y_original_pred))
RNN.evaluate(X_test,y_test,batch_size = 64)

[[147   1   5]
 [  3 140   5]
 [ 12   8 314]]
20/20 [==============================] - 0s 2ms/step - loss: 0.5355 - accuracy: 0.9465


[0.5355382561683655, 0.9464566707611084]